spring:
  application:
    name: smartops-asset-app
  datasource:
    url: jdbc:postgresql://localhost:5432/smartops
    username: smartops
    password: smartops
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: asset
    default-schema: asset
    create-schemas: true
    table: flyway_schema_history

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: asset

server:
  port: 8082

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - ch.smart.operations.platform.shared.exceptions.DownstreamClientException
  timelimiter:
    instances:
      customerService:
        timeoutDuration: 2s
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
smartops:
  security:
    jwt:
      issuer: smartops-identity
      secret: ${SMARTOPS_JWT_SECRET:local-dev-secret-change-me-local-dev-secret-change-me}

logging:
  level:
    root: INFO
    org.hibernate.SQL: warn
