CREATE SCHEMA IF NOT EXISTS customer;
CREATE SCHEMA IF NOT EXISTS asset;
CREATE SCHEMA IF NOT EXISTS workorder;
CREATE SCHEMA IF NOT EXISTS billing;
CREATE SCHEMA IF NOT EXISTS notification;

GRANT ALL PRIVILEGES ON SCHEMA customer TO smartops;
GRANT ALL PRIVILEGES ON SCHEMA asset TO smartops;
GRANT ALL PRIVILEGES ON SCHEMA workorder TO smartops;
GRANT ALL PRIVILEGES ON SCHEMA billing TO smartops;
GRANT ALL PRIVILEGES ON SCHEMA notification TO smartops;